### ISSUE TITLE
ImportError: No module named _lldb error on Fedora 25

### ISSUE THREAD

**Issue by ghost** [FedoraSwift/fedora-swift#20]
When running `swiftbuild.sh build` on Fedora 25, I get the following error:

```
Command Output (stderr):
--
Traceback (most recent call last):
  File "/home/ezueled/tmp/swiftbuild/swift/utils/symbolicate-linux-fatal", line 30, in <module>
    import lldb
  File "/home/ezueled/tmp/swiftbuild/build/buildbot_linux/lldb-linux-x86_64/lib64/python2.7/site-packages/lldb/__init__.py", line 46, in <module>
    _lldb = swig_import_helper()
  File "/home/ezueled/tmp/swiftbuild/build/buildbot_linux/lldb-linux-x86_64/lib64/python2.7/site-packages/lldb/__init__.py", line 45, in swig_import_helper
    return importlib.import_module('_lldb')
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _lldb
Traceback (most recent call last):
  File "/home/ezueled/tmp/swiftbuild/swift/utils/backtrace-check", line 81, in <module>
    main()
  File "/home/ezueled/tmp/swiftbuild/swift/utils/backtrace-check", line 78, in main
    assert(found_stack_trace_entry)
AssertionError

--

********************
                      -- Testing: 8860 tests, 4 threads --                      
Testing Time: 716.34s
********************
Failing Tests (1):
    Swift(linux-x86_64) :: Runtime/linux-fatal-backtrace.swift

  Expected Passes    : 7894
  Expected Failures  : 71
  Unsupported Tests  : 894
  Unexpected Failures: 1
*** Failed while running tests for swift (check-swift-validation-linux-x86_64)
utils/build-script: fatal error: command terminated with a non-zero exit status 1, aborting
utils/build-script: fatal error: command terminated with a non-zero exit status 1, aborting
~/workspace/fedora-swift
``` 

Any hint about how to fix the `ImportError: No module named _lldb` error?

**Comment by ghost** [comment]
This error maybe come from master seems to use lldb 4.0.0 (not yet released I think) while 3.9.0 is installed.

I tried to update all repos to Swift 3.0.1 tag, but then I have this error:

```
../build/buildbot_linux/foundation-linux-x86_64
Foundation/NSURLSession/EasyHandle.swift:21:8: error: no such module 'Dispatch'
import Dispatch
       ^
[116/315] CompileC: CoreFoundation/Collections.subproj/CFBasicHash.c
ninja: build stopped: subcommand failed.
utils/build-script: fatal error: command terminated with a non-zero exit status 1, aborting
```

**Comment by ghost** [comment]
I succeeded to compile Swift on Fedora 25 with https://github.com/corinnekrych/swift-rpm/pull/4 by creating a RPM based on sources.
